### ISSUE TITLE
I can't remember my email and password everytime 🤔

### ISSUE THREAD

**Issue by harsh-100** [devashishsoni98/my-portfolio#2]
As  a user , truly speaking i don't like login using boring email and passwords 🙅.  I have already logged in my google account why would i do that again and again  ? . I want to login in your movie listing app , but i find out 😒 login system of email and password . 

Why don't you for me , as a user , use the firebase and check out how to apply the google login , where users like me don't have to put data again and again . It would be helpful for you to track users right ??

Thanks 😉
Will see if you make it in a way , what a user want❤️

**Comment by devashishsoni98** [comment]
Thank you for your feedback and suggestion! Adding a google login through firebase would be a great addition to the project and will improve user experience. I'll get started in implementing the Google Login for the login page using Firebase. 👍

**Comment by devashishsoni98** [comment]
**Update** : I have added the Google Sing-In feature using Firebase Authentication. I also added a secured Profile page to  which the user is redirected once they log in and it also displays their name (by collecting data once they are logged in), I have also added a Sign-Out feature which lets the user to log out and removes the user data.
I will fix the css styling for buttons and profile page soon. 👍

**Comment by harsh-100** [comment]
Great ! Now i loved the way i sign in here and don't need to remember passwords everytime . 

Few things in this story i need as a user 
 - After login please redirect me to the dashboard page (if any ) or redirect me to home page 
 - in navbar , show the avtar that i have in my google account , 
 - instead of logout show profile button , which will show a dropdown having my name or email and second is logout button 
 - on clicking email or name in profile dropdown , will take me to a profile page (design with the data you have of user from google auth )
 
Thanks 😉

**Comment by devashishsoni98** [comment]
Thank you for the suggestion. 👍
I have modified the code, after login , now the user will be redirected to home page first and there will be a dropdown button in navbar from where the user can access their personalized profile page as well as get the option to SignOut with a confirmation prompt. 
I have also added the avatar in the navbar which is based on the user's Gmail profile picture. 👨
On the profile page , I have displayed some of the key data which I thought can be placed on the profile page such as email, UID, last login and more. 
While testing the profile page , I found that if the page is refreshed it gives error as firebase takes some time to send the user information, to handle that delay , I have added conditional checks on components on profile page so that they are shown with blank information for few milliseconds until the data is received and changed to final state once the data is received. 👍

The CSS styling is not the best yet 😅, I am working on that ! 

Thank you for the detailed suggestion, the user experience is now much better than before. 👍👌

**Comment by devashishsoni98** [comment]
I have worked on the css now. Thank you for the suggestion. I would be happy to hear on what more I can improve upon. 👍

**Comment by SESMASANTHONY** [comment]
I can't recover my account anymore because I lost my number that I linked to my Gmail account do to getting busted for a traffic violation and not paying my phone bill I lost the number link to my account and who ever Gots the number doesn't respond or communication with me what so ever what could I do

**Comment by devashishsoni98** [comment]
@SESMASANTHONY I am sorry , I don't think I can help you with recovering your account. 😅
